USE codeup_test_db;

INSERT INTO album (artist, name, release_date, sales, genre)
VALUES('Micheal Jackson','Thriller',1982,70,'Pop, Post-Disco, Funk, Rock'),
		('AC/DC','Back in Black', 1980, 50, 'Hard Rock'),
		('Whitney Houston', 'The Bodyguard','1992',45,'R&B, Soul, Pop'),
		('Pink Floyd','The Dark Side of the Moon',1973,45,'Progressive Rock'),
		('Eagles','The Greatest Hits',1976,44,'Country Rock, Soft Rock, Folk Rock'),
		('Eagles','Hotel California',1976,44,'Soft Rock'),
		('Shania Twain','Come on Over',1997,40,'County, Pop'),
		('Fleetwood Mac','Rumours',1977,40,'Soft Rock'),
		('Bee Gees','Saturday Night Fever',1977,40,'Disco'),
		('Led Zeppelin','Led Zeppelin IV',1971,37,'Hard Rock, Heavy Metal, Folk Rock'),
		('Michael Jackson','Bad',1987,35,'Pop, Rythym & Blues, Funk, Rock'),
		('Meat Loaf','Bat Out of Hell',1977,34,'Hard Rock, Glam Rock, Progressive Rock'),
		('Alanis Morissette','Jagged Little Pill',1995,33,'Alternative Rock'),
		('Various Artists','Dirty Dancing',1987,32,'Pop, Rock, R&B'),
		('Celine Dion','Falling into you',1996,32,'Pop, Soft Rock'),
		('Adele','21',2011,31,'Pop, Soul'),
		('The Beatles','1',2000,31,'Rock'),
		('Metallica','Metallica',1991,31,'Heavy Metal'),
		('Celine Dion','Let''s Talk about Love',1997,31,'Pop, Soft Rock'),
		('Bob Marley & the Wailers','Legend: The Best of Bob Marley & the Wailers',1984,30,'Reggae'),
		('Guns N'' Roses','Appetite for Destruction',1987,300,'Hard Rock'),
		('Bruce Springsteen','Born in the U.S.A.',1984,30,'Heartland Rock'),
		('ABBA','Gold: Greatest Hits',1992,30,'Pop, Disco'),
		('Dire Straits','Brothers in Arms',1985,30,'Roots Rock, Blues Rock, Soft Rock'),
		('Santana','Supernatural',1999,30,'Latin Rock'),
		('Madonna','The Immaculate Collection',1990,30,'Pop, Dance'),
		('Pink Floyd','The Wall',1990,30,'Progressive Rock'),
		('The Beatles','Sgt. Pepper''s Lonely Hearts Club Band',1967,30,'Rock'),
		('Michael Jackson','Dangerous',1991,30,'New Jack Swing, R&B, Pop'),
		('The Beatles','Abbey Road',1969,30,'Rock');
